# Generated by Django 5.2.7 on 2025-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок поста",
                        max_length=50,
                        verbose_name="Заголовок поста",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите содержимое поста",
                        verbose_name="Содержимое поста",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью",
                        null=True,
                        upload_to="blogs/photo",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания товара",
                        verbose_name="Дата создания товара",
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Установите статус поста",
                        verbose_name="Статус поста",
                    ),
                ),
                (
                    "number_of_views",
                    models.IntegerField(
                        help_text="Введите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["title", "is_posted"],
            },
        ),
    ]
