# Generated by Django 5.2.7 on 2025-12-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название категории",
                        max_length=50,
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание категории",
                        verbose_name="Описание категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование товара",
                        max_length=50,
                        verbose_name="Наименование товара",
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False,
                        help_text="Установите статус публикации",
                        verbose_name="Статус публикации ",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию товара",
                        null=True,
                        upload_to="catalog/photo",
                        verbose_name="Фото товара",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Введите категорию товара",
                        max_length=50,
                        verbose_name="Категория товара",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Введите цену за покупку товара",
                        verbose_name="Цена за покупку товара",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        help_text="Введите дату создания товара",
                        verbose_name="Дата создания товара",
                    ),
                ),
                (
                    "date_last_changed",
                    models.DateField(
                        help_text="Введите дату последнего изменения товара",
                        verbose_name="Дата последнего изменения товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "category"],
            },
        ),
    ]
